apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  selector:
    matchLabels:
      app: web_app
  template:
    metadata:
      labels:
        app: web_app
    spec:
      containers:
      - name: farming
        image: bharath3006/farming
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: config_web

---

