services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: farming
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongo:27017/farming_management
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo-data: