apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodeployment
spec:
  selector:
    matchLabels:
      app: mongo_web
  template:
    metadata:
      labels:
        app: mongo_web
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        
